### ISSUE TITLE
AWS elastic beanstalk environment health is severe . In the health check , we are getting below error 

### ISSUE THREAD

**Issue by Shweta-Sati** [aws/elastic-beanstalk-roadmap#243]
I have deployed a simple ASP.NET application with a single instance created behind a load balancer . 
The health of the environment appears as SEVERE and below errors are seen in the log file.
Could you please suggest me what changes can I do to rectify this

Below are the logs from the elastic beanstalk environment

**cfn_init.log**

2022-04-27 15:08:36,930 [INFO] Command schedulepublishlogs succeeded
2022-04-27 15:08:36,961 [INFO] ConfigSets completed
2022-04-27 15:08:36,976 [INFO] -----------------------Build complete-----------------------
2022-04-27 15:08:37,993 [INFO] -----------------------Starting build-----------------------
2022-04-27 15:08:38,148 [INFO] Running configSets: _AppInstall
2022-04-27 15:08:38,148 [INFO] Running configSet _AppInstall
2022-04-27 15:08:38,164 [INFO] Running config Hook-PreInit
2022-04-27 15:08:47,880 [INFO] Command hooks succeeded
2022-04-27 15:08:47,911 [INFO] Running config Hook-PostInit
2022-04-27 15:08:48,130 [INFO] Command hooks succeeded
2022-04-27 15:08:48,161 [INFO] Running config Hook-PreAppDeploy
2022-04-27 15:10:09,859 [INFO] Command hooks succeeded
2022-04-27 15:10:09,907 [INFO] Running config Hook-EnactAppDeploy
2022-04-27 15:10:22,911 [ERROR] Command hooks (HooksExecutor.exe appdeploy\enact) failed
2022-04-27 15:10:22,911 [ERROR] Error encountered during build of Hook-EnactAppDeploy: Command hooks failed
Traceback (most recent call last):
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command hooks failed
2022-04-27 15:10:22,927 [ERROR] -----------------------BUILD FAILED!------------------------
2022-04-27 15:10:22,927 [ERROR] Unhandled exception during build: Command hooks failed
Traceback (most recent call last):
  File "cfn-init", line 171, in <module>
  File "cfnbootstrap\construction.pyc", line 129, in build
  File "cfnbootstrap\construction.pyc", line 530, in build
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command hooks failed
2022-04-27 15:10:49,586 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.eu-west-1.amazonaws.com
2022-04-27 15:10:49,602 [DEBUG] Describing resource AWSEBAutoScalingGroup in stack arn:aws:cloudformation:eu-west-1:800810206054:stack/awseb-e-txgnymcpki-stack/f97466e0-bc9f-11ec-8f0a-022b2b903663
2022-04-27 15:10:51,187 [INFO] -----------------------Starting build-----------------------
2022-04-27 15:10:51,250 [INFO] Running configSets: InfoTask-TailLogs
2022-04-27 15:10:51,266 [INFO] Running configSet InfoTask-TailLogs
2022-04-27 15:10:51,280 [INFO] Running config InfoTask-TailLogs

**AWSDeployment.log:**

2022-04-27 15:10:13,531 INFO 1 AWSBeanstalkCfnDeployApp.DeployApp - Reading configuration from c:\Program Files\Amazon\ElasticBeanstalk\config\containerconfiguration
2022-04-27 15:10:13,750 ERROR 1 AWSBeanstalkCfnDeploy.DeploymentUtils - Exception during deployment.
Microsoft.Web.Deployment.DeploymentDetailedException: Object of type 'package' and path 'C:\cfn\ebdata\source_bundle_final.zip' cannot be created. 
 Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_EXCEPTION_WHILE_CREATING_OBJECT. ---> Microsoft.Web.Deployment.DeploymentException: 
 The Zip package 'C:\cfn\ebdata\source_bundle_final.zip' could not be loaded. ---> System.IO.FileNotFoundException: Could not find file 'C:\cfn\ebdata\source_bundle_final.zip'.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable`1 fileLength)
   at Microsoft.Web.Deployment.ZipFile.Load()
   at Microsoft.Web.Deployment.ZipPackageProvider..ctor(DeploymentProviderContext providerContext, DeploymentBaseContext baseContext, String path)
   --- End of inner exception stack trace ---
   at Microsoft.Web.Deployment.ZipPackageProvider.GetAttributes(DeploymentAddAttributeContext addContext)
   at Microsoft.Web.Deployment.DeploymentObject.EnsureValidAttributes()
   --- End of inner exception stack trace ---

**Comment by vhak24** [comment]
@Shweta-Sati : did you happened to find solution for this ?
