### ISSUE TITLE
Lock version of Puma in Ruby platforms

### ISSUE THREAD

**Issue by ghclanton** [aws/elastic-beanstalk-roadmap#98]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
In issue #38 it was requested to use newer versions of Ruby and Passenger.  It looks like this was done not only for the AL2 platform but also AL1 which I run (Puma with Ruby 2.6 running on 64bit Amazon Linux/2.11.x).  Yesterday during a deployment the brand new puma 5.0.0 was deployed which resulted in puma no longer working and production downtime.  This was caused by a newly deprecated option still being in the default beanstalk rubyconf.rb config file (daemonize false).

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Puma with Ruby 2.6 running on 64bit Amazon Linux/2.11.x but possibly others.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Ideally, I would like to be able to lock the puma version on our deployments so we can choose when to upgrade to a new version.  If that isn't possible, then there should be some basic testing and approval of new versions before they are used in beanstalk.  The beanstalk environment with default configuration was completely broken yesterday (and may still be.)

**Are you currently working around this issue?**
I used an ebextension to remove the bad configuration line in the config file.

**Additional context**
Error:
```
Traceback (most recent call last):
        12: from /opt/rubies/ruby-2.6.5/bin/puma:23:in `<main>'
        11: from /opt/rubies/ruby-2.6.5/bin/puma:23:in `load'
        10: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/bin/puma:8:in `<top (required)>'
         9: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/bin/puma:8:in `new'
         8: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/lib/puma/cli.rb:71:in `initialize'
         7: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/lib/puma/cli.rb:71:in `new'
         6: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/lib/puma/launcher.rb:59:in `initialize'
         5: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/lib/puma/configuration.rb:205:in `load'
         4: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/lib/puma/configuration.rb:205:in `each'
         3: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/lib/puma/configuration.rb:205:in `block in load'
         2: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/lib/puma/dsl.rb:47:in `_load_from'
         1: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/puma-5.0.0/lib/puma/dsl.rb:47:in `instance_eval'
/opt/elasticbeanstalk/support/conf/pumaconf.rb:9:in `_load_from': undefined method `daemonize' for #<Puma::DSL:0x00005584f072b620> (NoMethodError)
```

**Comment by fitohoyos** [comment]
@ghclanton  Could you please share how your workaround looks like?

**Comment by toh2526** [comment]
> @ghclanton Could you please share how your workaround looks like?

Maybe by creating a custom file in .ebextensions

```
files:
  "/opt/elasticbeanstalk/support/conf/pumaconf.rb":
    mode: "000644"
    owner: root
    group: root
    content: |
      directory '/var/app/current'
      threads 8, 32
      workers %x(grep -c processor /proc/cpuinfo)
      bind 'unix:///var/run/puma/my_app.sock'
      pidfile '/var/run/puma/puma.pid'
      stdout_redirect '/var/log/puma/puma.log', '/var/log/puma/puma.log', true
```
